# Posting stats tutorials

The PsyTeachR team maintains [a web page with various data analysis tutorials](https://psyteachr.github.io/tutorials). These are generally walkthroughs using R of data wrangling, plotting, or statistical topics; usually things that students frequently ask about but that we couldn't fit in one of our online books. If you have an idea for a tutorial that you'd like to create (mediation analysis?), please contact <a href="mailto:dale.barr@glasgow.ac.uk">Dale</a>.

Your tutorial should be a standalone RMarkdown file. By 'standalone' I mean that the Rmd file should be all that is needed: any data or image files needed in the demo should either be pulled down from a web URL or should be generated by the script.

The RMarkdown file should include a YAML header, and *must* include the fields `title`, `author`, `date`, and `category`. For category, choose one of the existing categories listed on the [tutorial page](https://psyteachr.github.io/tutorials); if none fit, then you can create a new category. Here is an example of YAML for a tutorial that uses the [`{webex}`](https://github.com/PsyTeachR/webex) package for interactivity. If you don't need `{webex}` then set `output` to `html_document`. Further examples are available in the [repository](https://github.com/psyteachr/tutorials).

```
---
title: Converting string values to numeric values for questionnaire scoring
author: Dale Barr
date: "August 18, 2021"
category: "Questionnaire Data"
output: webex::webex_default
---
```

## How to add your tutorial

Once you've created and debugged your RMarkdown file, adding your tutorial can be achieved in four simple steps:

1. clone the repository from <https://github.com/psyteachr/tutorials>
2. copy your RMarkdown file into the `content` subdirectory
3. rebuild the site by either:
   - opening and knitting the `index.Rmd` file, or
   - running `make` in the repository main directory.
4. push the changes back to github.

