---
title: "Annoying Sh*t That I Figured Out But Will Soon Forget"
author: "Dale Barr"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: dalejbarr/annoying-sh-t
description: "As it says on the tin."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About this book

## Audience

This book is for staff at the Institute of Neuroscience and Psychology / School of Psychology at the University of Glasgow. Any opinions expressed herein do not reflect those of the Institute or School, or the University of Glasgow.

## How it works

1. Figure out how to do something that you probably figured out many times before and forgot. (I take a generous view of what it means to "figure something out": if you ask someone and they tell you, that counts.)

2. Get annoyed at how difficult it was to figure out how to do the thing that you probably once knew and then forgot.

3. Wish that you had a reliable way to keep track of such things.

4. Stew in your annoyance at hard-to-learn-easy-to-forget trivial sh*t until your brain reminds you of this resource.

5. Open this page and find the chapter with your topic in the floating table of contents. If it doesn't exist, ask Dale to make the chapter.

6. If you just have a quick edit or are not comfortable with git, click the edit icon in the title bar at the top of the page. This will lead you to the source RMarkdown file in [the repository](https://github.com/dalejbarr/annoying-sh-t) where you can enter details about your annoying thing. Below your entry put your name and the date below it in italics (put an asterisk before and after the text.) Fancy people can do these stages by forking and cloning the repo, committing updates and submitting a pull request. Once your changes have been accepted, the book will be re-rendered and the website will be updated.

7. Remind yourself that this resource is called `annoying-sh-t` so you'll be more likely to remember it the next time you encounter annoying sh*t.

8. Bask in the momentary glory of knowing that you've saved others and your future self time and headaches.
